### ISSUE TITLE
Game links are blocked on Securly

### ISSUE THREAD

**Issue by pman5534** [red-stone-network/clockwork#1]
games are blocked on Securly for Chromebooks

**Comment by lukasexists** [comment]
Check if <a href="https://github.io/">this site</a> is blocked.

**Comment by lukasexists** [comment]
Alright, so it may just be a problem with the one site I sourced it all from. Give me a few hours and it should be fixed.

**Comment by pman5534** [comment]
ok.
 it ok

**Comment by lukasexists** [comment]
now it should be fixed. please try now

**Comment by pman5534** [comment]
it works now
ty
