### ISSUE TITLE
apps not showing: can't scroll on popup.

### ISSUE THREAD

**Issue by Hellscap3d** [red-stone-network/clockwork#10]
**Describe the bug**

title

**To Reproduce**
1. open clockwork on chromebook
2. install something
3. app not showing

**Expected behavior**
I would expect it to work
**Screenshots**
![image](https://user-images.githubusercontent.com/72767525/219393982-02f57e14-e9cb-45f9-9883-f7ced96243ff.png)

**Desktop (please complete the following information):**
 - OS: chromeos
 - Browser chrome
 - Version latest

**Additional context**

**Comment by Hellscap3d** [comment]
basically the apps are hidden and I cant scroll to em

**Comment by lukasexists** [comment]
scroll down on the bottom, or better yet, just fullscreen the window

there is literally a scroll bar

**Comment by lukasexists** [comment]
Also, for future reference, you can scroll on your navbar if it overfills.

**Comment by Hellscap3d** [comment]
thanks
