### ISSUE TITLE
new bookmarklet does not work

### ISSUE THREAD

**Issue by Hellscap3d** [red-stone-network/clockwork#12]
it doesnt lol

**Comment by alexnm27** [comment]
https://redstone-nw.netlify.app/clockwork-app/index.html

**Comment by lukasexists** [comment]
Sorry for breaking it, please use the script in script.js as a bookmarklet instead for now. Thanks

**Comment by lukasexists** [comment]
JUST FIXED IT - try the new one in bookmarklet.js.
