### ISSUE TITLE
Bookmarklet Error

### ISSUE THREAD

**Issue by SAK2050** [red-stone-network/clockwork#16]
When I click the bookmarklet the window does not open no matter what website I am on. This is on the newest version

**Comment by lukasexists** [comment]
Go to this site:
`chrome://policy`
Then search for URLBlocklist. Once you find it, on the opposite side of the box it is in, you should see a button that says "Show more". Click it. Then copy the list of websites that show and send them to us here.

**Comment by SAK2050** [comment]
"chrome-extension://nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html",
  "chrome-extension://pnhechapfaindjhompbnflcldabbghjo/html/crosh.html",
  "chrome-extension://pnhechapfaindjhompbnflcldabbghjo/html/nassh.html",
  "chrome-untrusted://crosh",
  "chrome://inspect",
  "https://sites.google.com/view/theadvancedmethod/home",
  "https://sites.google.com/view/games-unblockedd/",
  "https://sites.google.com/site/unblockedgames66ez/",
  "https://sites.google.com/view/unblockedgameswtf2/",
  "https://sites.google.com/site/funblocked77/",
  "https://sites.google.com/site/unblockedgame76/",
  "https://sites.google.com/site/besthackedgames/",
  "https://sites.google.com/site/thegamecompilation/",
  "https://sites.google.com/site/tyroneunblockedgame/",
  "https://www.sites.google.com/site/hackedunblockedbeast/",
  "https://www.sites.google.com/site/unblockedgamestop/",
  "https://m.sites.google.com/site/iounblockedgames/",
  "https://scratch.mit.edu/"

**Comment by SAK2050** [comment]
@lukasexists see above

**Comment by MicroChipKali** [comment]
We have the same issue...

**Comment by lukasexists** [comment]
You may be using the wrong site. Test it out on https://example.com/ .

**Comment by lukasexists** [comment]
Closing for now. Please read new instructions in readme.md
