### ISSUE TITLE
Hellcord: My fosscord instance (custom discord, not on the official servers)

### ISSUE THREAD

**Issue by Hellscap3d** [red-stone-network/clockwork#18]
**Put your app/theme's link here.**
https://hellscaped-cw-plugins.netlify.app/hellcord.js
**Put your app/theme's name here.**
Hellcord
**Put a small description of your app/theme here.**
Hellcord is a Fosscord instance meant to be used at school.
There is little ToS, but you still need to be family friendly.

**Comment by lukasexists** [comment]
gimme a bit and ill add it

**Comment by lukasexists** [comment]
Your template isn't on the latest version. Update it and I'll add it.

**Comment by Hellscap3d** [comment]
> Your template isn't on the latest version. Update it and I'll add it.

Alright

**Comment by Hellscap3d** [comment]
> Your template isn't on the latest version. Update it and I'll add it.

Also i tweaked the template so it would actually work. The current one only shows a blank page.

**Comment by lukasexists** [comment]
Still not on the latest version... Update it to [the 0.14.0 template](https://github.com/red-stone-network/clockwork/blob/main/app-template.js) and I'll add it.

**Comment by Hellscap3d** [comment]
> Still not on the latest version... Update it to [the 0.14.0 template](https://github.com/red-stone-network/clockwork/blob/main/app-template.js?rgh-link-date=2023-03-02T14%3A52%3A25Z) and I'll add it.

Just realized what you mean- Just added the lines that were added in the 0.14.0 template and changed it in the comment.

**Comment by Hellscap3d** [comment]
Also if you install it you'd notice that it has a little logo on it, I realized I could do that by putting an img in the title.

**Comment by Hellscap3d** [comment]
Feel free to make a server for Clockwork on there.

**Comment by lukasexists** [comment]
This app seems to link to a scummy website! Please host this service on something else and create a new issue.

**Comment by Hellscap3d** [comment]
> This app seems to link to a scummy website! Please host this service on something else and create a new issue.

Wrong, google just flagged it falsely. This often happens with fosscord. https://github.com/fosscord/fosscord-server
I'm working on getting it unflagged (aka reporting the false flag to google)
