### ISSUE TITLE
manual html not working

### ISSUE THREAD

**Issue by bluehalooo** [red-stone-network/clockwork#19]
**Describe the bug**
When I attempt to use manual html, it just ends up saying "www.google.com refused to connect."
**To Reproduce**
I just did the steps said in the manual html

**Expected behavior**
I expected for the application for launch
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Google OS
 - Browser Chrome

**Comment by bluehalooo** [comment]
If it helps, here is the URL blocklist:

chrome://flags,chrome://inspect,chrome-extension://nkoccljplnhpfnfiajclkommnmllphnl/html/crosh.html,chrome://settings/accountManager,chrome://os-settings/accountManager,chrome://os-settings/people,chrome://chrome-signin,youtube.com/logout,https://chrome.google.com/webstorex,http://chrome.google.com/webstorex,chrome://version,chrome://net-export,sh1mmer.me,alicesworld.tech,luphoria.com,bypassi.com,github.com/3kh0/ext-remover

**Comment by lukasexists** [comment]
The windows may be getting blocked. Click the lock in the top right, then click Site settings. Then find Pop-ups and redirects, and make sure that's enabled. Also keep in mind there are plenty of HTML editors online that this method will still work on.

**Comment by lukasexists** [comment]
Have you tried it, and if you did, did it work?

**Comment by bluehalooo** [comment]
i did, it did not work :(

**Comment by Hellscap3d** [comment]
Thats the GTFO function in action. Delete the gtfo function in the source code maybe?

**Comment by bluehalooo** [comment]
@Hellscap3d I deleted the GTFO function in the code that I was supposed to run, and that just made it say "Loading..." forever. It might be embedded deeper in the code I'm importing.

**Comment by bluehalooo** [comment]
Also, if I change the link to bing.com, then it does launch bing.

**Comment by bluehalooo** [comment]
Found the issue, it was that my school's firewall was blocking something vital for it to work. (I might open a pull request to fix this)
