### ISSUE TITLE
Developer used wrong src

### ISSUE THREAD

**Issue by a1exsDev** [red-stone-network/clockwork#21]
In the guide on how to use the bookmarklet, it said to copy and paste the code into the URL area, which I did. So I went to [example.com](example.com) and it changed the HTML to "//redstone-nw.netlify.app/assets/clockwork-bookmarklet.js" as plain text. I reviewed the code and saw that you did not put the full site address which would be "https://redstone-nw.netlify.app/assets/clockwork-bookmarklet.js". So I fixed it and it worked. Just changed the bookmarklet of the GitHub repo to s.src="https://redstone-nw.netlify.app/assets/clockwork-bookmarklet.js"

**Comment by lukasexists** [comment]
I'm not reading this - please use an issue template
