### ISSUE TITLE
Make everything based on the github repository

### ISSUE THREAD

**Issue by bluehalooo** [red-stone-network/clockwork#22]
**Is your feature request related to a problem? Please describe.**
Yes, it is. Not doing this causes an issue where it doesn't work if the website is blocked.

**The Problem**
I want everything to be based on the GitHub repositories, instead of scripts found on the websites. For example, some of the code references HTML from the website, and sometimes outright just iframes the website. This makes it impossible to use the bookmarklet if the website is blocked or firewalled.

You can add different versions of the bookmarklet/HTML where all of the scripts are taken off of the GitHub repository link, instead of the website links, so even if the website gets blocked then you can still access the bookmarklet and manual HTML unless the repository link itself gets blocked.

**Comment by bluehalooo** [comment]
sorry if my explanation is a little vague

**Comment by Hellscap3d** [comment]
other idea: data uris.

Impossible to be blocked.
They resolve in the browser, not the internet.

**Comment by lukasexists** [comment]
Also, thank you for using a template!

**Comment by lukasexists** [comment]
I'm also gonna add this: Gitlab is objectively better than Github. The only reason this exists is because we're trying to get a decent-sized userbase.
