### ISSUE TITLE
No themes are in store.

### ISSUE THREAD

**Issue by SAK2050** [red-stone-network/clockwork#23]

**Comment by lukasexists** [comment]
we're working on it

**Comment by lukasexists** [comment]
As a temporary solution, you can now add themes by URL:
Go to **Settings > Add Theme By URL**.

Here are the URLs to some themes:
- https://redstone-nw.netlify.app/clockwork-app/clockstyle.css (Windows Knockoff)
- https://redstone-nw.netlify.app/clockwork-app/codestyle.css (Code Terminal)

We're working as fast as we can on adding themes right now, but you have to be patient.

**Comment by lukasexists** [comment]
It's done.
