### ISSUE TITLE
If https://redstone-nw.netlify.app/assets/clockwork-bookmarklet.js is blocked, well, too bad

### ISSUE THREAD

**Issue by fartsindogs** [red-stone-network/clockwork#24]
**Describe the bug**
Wont ever work if https://redstone-nw.netlify.app/assets/clockwork-bookmarklet.js is blocked
**To Reproduce**
1.  have https://redstone-nw.netlify.app/assets/clockwork-bookmarklet.js blocked
2. try and fail to use

**Expected behavior**
For whatever clockwork is suppost to do
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version don't know but doesent matter

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukasexists** [comment]
We host Clockwork on Netlify. That will not change unless you can find a better service. Sorry.
