### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Phoenix132** [red-stone-network/clockwork#25]
I tried all the methods to access browser. It opens a new window that flashes the word Loading or Load, and then its a black screen.
I'm on Windows 10, Google Chrome, any help??

**Comment by lukasexists** [comment]
Please use a template when creating issues!

Try resetting your cookies for the website and reloading the page.

**Comment by lukasexists** [comment]
Did that fix it?

**Comment by lukasexists** [comment]
Issue is dead - closing!
