### ISSUE TITLE
games dont work

### ISSUE THREAD

**Issue by murayamaHL** [red-stone-network/clockwork#32]
**Describe the bug**
games are not showing up on navbar  

**To Reproduce**
1. Go to app store 
2. Click on any app
3. look at navbar  

**Expected behavior**
games should pop up on navbar  

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by murayamaHL** [comment]
what do you mean by viewing with sidetracked?

**Comment by lukasexists** [comment]
I didn't say anything about it, but you can find it [here](https://github.com/red-stone-network/bypass-central/blob/main/monitoring-extensions/side-panel.md).

Also please answer the questions.

**Comment by lukasexists** [comment]
Issue is dead, closing...
