### ISSUE TITLE
Glitch not working

### ISSUE THREAD

**Issue by urmom345** [red-stone-network/clockwork#37]
I love clockwork and its idea except for one main feature. Most of its apps and services use glitch.me and glitch is blocked in my school. Will clockwork ever switch to a website other than glitch for its appstore and other services?

One solution could be using another free website hosting service that integrated the same way

**Comment by lukasexists** [comment]
We're working with some people to try and get the Glitch-based app store unblocked. However, you'll have to wait for Clockwork v2 to release.

In the meantime, you can go to Settings > Classic App Store to install apps from a curated list.

**Comment by urmom345** [comment]
Is there A curated list I can install through the custom app install like on GitHub?
