### ISSUE TITLE
Suggest adding a proxy browser or something related to it

### ISSUE THREAD

**Issue by Phoenix132** [red-stone-network/clockwork#41]
I was thinking of an addition of a browser or vpn browser to Clockwork. Something like opera's vpn browser. It would surely make the "OS in your browser" complete!!

Please add this feature, but if you cannot, it's alright 😄

**Comment by lukasexists** [comment]
I've created an app for it in Clockwork V2, but as of right now we aren't accepting new Clockwork V1 apps for the app store. Clockwork V2 should come out sometime in May/June, so you might have to wait a little while. Sorry.
