### ISSUE TITLE
Rehosting options?

### ISSUE THREAD

**Issue by IcyonGit** [red-stone-network/clockwork#46]
**Is your feature request related to a problem? Please describe.**
Would love to have the ability to rehost

**Describe the solution you'd like**
Please let me rehost

**Describe alternatives you've considered**
Rehost please

**Additional context**
Rehost

**Comment by lukasexists** [comment]
That's a good idea for a feature, however we won't be adding it to v1 - you'll likely have to wait for v2 to come out.

Also, please answer the questions correctly on the template.
