### ISSUE TITLE
404 NOT_FOUND while working on an app

### ISSUE THREAD

**Issue by Shibedev12** [red-stone-network/clockwork#55]
Followed The Wiki Tutorial, Popped In My Name, URL, Title, etc..... And It Looked To Be Working. I Installed The App, Then When I Opened The App, It Said, 404: NOT_FOUND. I Will Attach A Screenshot If You Guys Can Help Lmao
![image](https://github.com/red-stone-network/clockwork/assets/100108102/c24a50a5-d348-4d0d-bea8-7203894ce796)
See?
Wiki Said Nothing About This.
Cheers To My Fellow GoGuardian Haters!
-Shibe

**Comment by Adhdbarn** [comment]
I think you forgot to change the URL

**Comment by lukasexists** [comment]
I think this is probably a problem with the app itself. Could you please send the .json file over?

**Comment by adonzone** [comment]
where is da wiki

**Comment by Adhdbarn** [comment]
https://github.com/red-stone-network/clockwork/wiki

**Comment by Shibedev12** [comment]
Sure!
https://gistcdn.githack.com/Shibedev12/c1c773b92f400fa7776adc84babc78df/raw/404b7bb0a0df72d4f9b09526a8e29f87bcb515ef/app.json

**Comment by Adhdbarn** [comment]
i think i fixed it, replace your code with this and update the app in clockwork

{
  "name": "Metallic",
  "desc": "Metallic Proxy for Clockwork",
  "url": "https://usemetallic.com",
  "encodedUrl": "no",
  "icon": "https://redstone-nw.netlify.app/assets/icon.png",
  "author": "Shibedev12",
  "permissions": [installApp]
}

**Comment by Adhdbarn** [comment]
or just replace metallic with this
https://drive.google.com/file/d/1-dpUDJz0SpEg3r3ltjhUg7ITpfGclF8E/view?usp=sharing

**Comment by lukasexists** [comment]
no, the problem is that you need to remove installApp
