### ISSUE TITLE
App Store Isn't Loading

### ISSUE THREAD

**Issue by eyesmad** [red-stone-network/clockwork#56]
**Describe the bug**
When going to the V2 app store, it just won't load. This is the same with Munster.(They are just stuck loading.)
**To Reproduce**
1. Be on Clockwork V2
2. Click app store
3. idk

**Expected behavior**
I expected the V2 app store to open. 

**Clockwork information (please include):**
v2.0.0.0-beta14 at clockwork-os.vercel.app
Running Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by simpansoftware** [comment]
@lukasexists mark this as done, glitch was just down

**Comment by lukasexists** [comment]
damn lol
