### ISSUE TITLE
Page blocked by chrome

### ISSUE THREAD

**Issue by TheOnlyTGKK** [red-stone-network/clockwork#57]
When you open the app store and download an app it says "page blocked by chrome"

1.  open the app store
2. download an app
3. open it
4. page blocked by chrome

**Comment by simpansoftware** [comment]
can you try to self host

**Comment by simpansoftware** [comment]
i have a self host here: simpansoftware.github.io/clwork

**Comment by lukasexists** [comment]
1. self-hosting should solve this
2. use the templates please

**Comment by lukasexists** [comment]
Self-hosting won't solve this. You'll need to use a proxy (you can set a proxy in Settings > Proxy Settings. [More info here.](https://github.com/red-stone-network/clockwork/wiki/User-Guide#use-an-ultraviolet-proxy-with-clockwork-apps))
