### ISSUE TITLE
Clockwork store blocked

### ISSUE THREAD

**Issue by theoxideperson** [red-stone-network/clockwork#59]
**Describe the bug**
Clcokwork store is blocked by securly. It says site is in global block list.
**To Reproduce**
1. Go to 'clockwork.html'
2. Click on 'App Store'
3. See error

**Expected behavior**
I expected to see the store so that I can install something.

**Clockwork information (please include):**
v2.0.0.0-beta14 at clockwork-os.vercel.app
Running Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (khtML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by lukasexists** [comment]
This isn't a bug. Use the Proxy Settings in the Settings app to get around this
