### ISSUE TITLE
Unsaved apps again

### ISSUE THREAD

**Issue by wow2302** [red-stone-network/clockwork#60]
Bug with apps not saving on html and htm versions again. My clockwork apps that I installed save on the about blank version are are usable. Not on the .htm or .html versions of clockwork however.

How to reproudce bug:
1.Go to htm or html version of clockwork
2.Look at the hud and see your apps are not there even though you donwloaded from the clockwork app store

Saves my apps on about:blank version but not .htm or .hmtl versions of clockwork please go fix it.

**Comment by lukasexists** [comment]
This isn't a bug. The about:blank version and file versions have different areas of localStorage, meaning we can't fix this. However, you will be able to use the Import & Export tool in Clockwork to port it over soon.

**Comment by lukasexists** [comment]
Do not create multiple issues for one problem.

**Comment by lukasexists** [comment]
#58

**Comment by lukasexists** [comment]
If you do not respond soon, I will close this issue.
