### ISSUE TITLE
"Please enable Cookies and reload the page."

### ISSUE THREAD

**Issue by lolthisisanalt** [red-stone-network/clockwork#7]
I received this message while going on Quizlet.com what does it mean?Also why are the websites taking so long to load?

**Comment by owenl3744** [comment]
If you're using Chrome, press the lock button that is on the left of the URL (link to the website). Then press cookies. After that allow that website to have access to cookies.

**Comment by lukasexists** [comment]
Shadow is a proxy not made by me or anyone I really know. If it's slow, or websites break, I can't do anything about it.

I'd suggest you open an issue on Shadow for this. https://github.com/FogNetwork/Shadow
