### ISSUE TITLE
how do i make a layout?

### ISSUE THREAD

**Issue by pman5534** [red-stone-network/clockwork#9]
can you tell me how?

**Comment by lukasexists** [comment]
Do you mean a theme? If you do, use [this CSS file](https://redstone-nw.netlify.app/clockwork-app/clockstyle.css) as a template.

**Comment by lukasexists** [comment]
Once you're done, [create an issue here.](https://github.com/red-stone-network/clockwork/issues/new?assignees=&labels=enhancement&template=add-app-or-theme-to-clockwork-app-store.md&title=)

And if you mean rearranging apps on the app bar, you can't do that right now. Sorry.
